version: '3'

services:
  app:
    build:
      args:
        uid: 1000
        user: forum
      context: .docker
    container_name: forum
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - nginx
    volumes:
      - .:/var/www/html
    networks:
      - forum

  mysql:
    image: mariadb:10.5
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_DATABASE: '${DB_DATABASE:-forum}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - forum

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - forum

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - forum

  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - forum

networks:
  forum:

volumes:
  mysql_data:
  redis_data:
